.TH s/qmail: qmail-badmimetype 8
.SH NAME
qmail-badmimetypes \- prepare badmimetypes for qmail-smtpd
.SH SYNOPSIS
.B qmail-badmimetype
.SH DESCRIPTION
.B qmail-badmimetypes
reads the instructions in
.B HOME/control/badmimetypes
and writes them into
.B HOME/control/badmimetypes.cdb
in a binary format suited
for quick access by
.BR qmail-smtpd .

If there is a problem with
.BR control/badmimetypes ,
.B qmail-badmimetypes
complains and leaves
.B control/badmimetypes.cdb
alone.

.B qmail-badmimetypes
ensures that
.B control/badmimetypes.cdb
is updated atomically,
so
.B qmail-smtpd
never has to wait for
.B qmail-badmimetypes
to finish.
However,
.B qmail-badmimetypes
makes no attempt to protect against two simultaneous updates of
.BR control/badmimetypes.cdb .
For convenience,
.B qmail-badmimetypes
allows comments (lines starting with '#') and 
copies only the significant leading characters to
.BR control/badmimetypes.cdb .

The binary
.B control/badmimetypes.cdb
format is portable across machines.
.SH "SEE ALSO"
qmail-smtpd(8)
