.TH s/qmail: qmail-badloadertypes 8

.SH "NAME"
qmail-badloadertypes \- prepare badloadertypes for qmail-smtpd
.SH SYNOPSIS
.B qmail-badloadertypes

.SH "DESCRIPTION"
.B qmail-badloadertypes
reads the instructions in
.B QMAIL/control/badloadertypes
and writes them into
.B QMAIL/control/badloadertypes.cdb
in a binary format suited
for quick access by
.BR qmail-smtpd .

If there is a problem with
.BR control/badloadertypes ,
.B qmail-badloadertypes
complains and leaves
.B control/badloadertypes.cdb
alone.

.B qmail-badloadertypes
ensures that
.B HOME/control/badloadertypes.cdb
is updated atomically,
so
.B qmail-smtpd
never has to wait for
.B qmail-badloadertypes
to finish.
However,
.B qmail-badloadertypes
makes no attempt to protect against two simultaneous updates of
.BR control/badloadertypes.cdb .
For convenience,
.B qmail-badloadertypes
allows comments (lines starting with '#') and 
copies only the significant leading characters to
.BR control/badloadertypes.cdb .

The binary
.B control/badloadertypes.cdb
format is portable across machines.
.SH "SEE ALSO"
qmail-smtpd(8)
