.TH s/qmail: tai64nfrac 5
.SH NAME
tai64nfrac \- evaluate the TAI64 timestamp and write the fractional seconds
.SH SYNOPSIS
.B tai64nfrac

.SH DESCRIPTION
Reads a TAI64N external format timestamp following the '@' 
as first character from 
.I stdin 
and
writes the fractional seconds since epoch (TAI, not UTC) to 
.IR stdout .
Returns the following characters after the timestamp unaltered.

.SH "SEE ALSO"
tcpserver(1),
sslserver(1).
