#!/bin/sh

. ./conf-build

#********************************************************************************
# bin:
mkdir -p $QMAILDIR/bin  #/plugins

cp bouncesaying condredirect datemail except forward maildir2mbox \
   maildirmake mailsubj mksrvrcerts mkrsadhkeys predate preline $QMAILDIR/bin
cp qmail-bfque qmail-bfrmt qmail-clean qmail-fixq qmail-getpw qmail-inject \
   qmail-local qmail-lspawn qmail-newmrh qmail-newu qmail-print qmail-pw2u \
   qmail-qmqpc qmail-qmqpd qmail-qmtpd qmail-qread qmail-qstat \
   qmail-queue qmail-remote qmail-rspawn qmail-send qmail-shcfg \
   qmail-smtpd qmail-start qmail-tcpok qmail-tcpto              $QMAILDIR/bin
cp qreceipt sendmail splogger tcp-env                           $QMAILDIR/bin
cp qmail-tcpsrv tcprules                                        $QMAILDIR/bin

chown $USRM:$GRPQ  $QMAILDIR/bin/*
chmod 0755         $QMAILDIR/bin/*

cd "$QMAILDIR/bin"
chmod 0711 qmail-getpw qmail-local qmail-remote qmail-rspawn \
           qmail-clean qmail-send qmail-pw2u splogger
chmod 0700 qmail-lspawn qmail-start qmail-newu qmail-newmrh
cd $OLDPWD

#********************************************************************************
# doc

#********************************************************************************
# etc
mkdir $QMAILDIR/etc
chgrp $GRPS $QMAILDIR/etc

#********************************************************************************
# man
#for i in 1 5 7 8 ; do
#  [ -d $QMAILDIR/man/man$i ] || mkdir -p $QMAILDIR/man/man$i
#  cp man/$i/* $QMAILDIR/man/man$i
#done

#chmod -R 0644 $QMAILDIR/man
#chmod 0755 $QMAILDIR/man $QMAILDIR/man/*

#********************************************************************************
# tmp
mkdir $QMAILDIR/tmp
chgrp $GRPS $QMAILDIR/tmp
chmod 0777  $QMAILDIR/tmp

#********************************************************************************
# var:
# alias and users dir
mkdir -p $QMAILDIR/var/alias
mkdir -p $QMAILDIR/var/users
chown -R $USRM:$GRPS $QMAILDIR/var
chown    $USRA       $QMAILDIR/var/alias
chmod    2755        $QMAILDIR/var/alias
# create standard aliases --> move this to mkconfig
cd $QMAILDIR/var/alias
touch .qmail-root
echo root > .qmail-postmaster
[ -L .qmail-mailer-daemon ] || ln -s .qmail-postmaster .qmail-mailer-daemon
chmod 644 .qmail-*
../bin/maildirmake .Maildir 2>/dev/null
cd $OLDPWD

# queue
T=$QUEUEDIR     # just to shortening next commands (T: tmp)
mkdir -p $T/bounce $T/lock $T/pid
i=0
#until [ $i -eq `head -1 conf-split` ]
until [ $i -eq "$SPLIT" ]
do
  # Create splitted queue subdirectories
  mkdir -p $T/info/$i $T/intd/$i $T/local/$i $T/mess/$i $T/remote/$i $T/todo/$i
  i=$(($i+1))
done
# set all:
chown -R $USRQ:$GRPS  $QUEUEDIR
chmod -R 0750         $QUEUEDIR
# set new: bounce, info, local, remote
chown -R $USRS:$GRPS  $T/bounce $T/info $T/local $T/remote
chmod -R 0700         $T/info $T/intd $T/local $T/pid $T/remote
# on an upgrade: set correct mode of files (messages) (like in qmail-fixq)
find $QUEUEDIR/ -type f -exec chmod 644 {} + -exec chown $USRQ:0 {} +

# special files in 'lock'
dd if=/dev/zero of=$QUEUEDIR/lock/tcpto bs=2048 count=1 2>/dev/null
chown $USRR:$GRPS  $QUEUEDIR/lock/tcpto
chmod 0644         $QUEUEDIR/lock/tcpto

touch $QUEUEDIR/lock/sendmutex
chown $USRS:$GRPS  $QUEUEDIR/lock/sendmutex
chmod 0600         $QUEUEDIR/lock/sendmutex

mkfifo             $QUEUEDIR/lock/trigger 2>/dev/null
chown $USRS:$GRPS  $QUEUEDIR/lock/trigger
chmod 0622         $QUEUEDIR/lock/trigger

#********************************************************************************
# at least set rights and group of the home dir
chmod 755 $QMAILDIR ; chgrp $GRPS $QMAILDIR

#./mkconfig
