#!/bin/sh
shout() { echo "$0: $@" >&2; }
barf() { shout "fatal: $@"; exit 111; }
safe() { "$@" || barf "cannot $@"; }

here=`env - PATH=$PATH pwd`
mypwd=${here%package}
mypwd=${mypwd%/}
home=`head -1 $mypwd/conf-home`

if [ -d $home ] 
then
  shout "Keeping directory $home."
  shout "The queue directory will use now bigtodo ..."
else
  safe mkdir -p $home
fi 

exit 0
