#!/bin/sh
shout() { echo "${0}: $@" >&2; }
barf() { shout "fatal: $@"; exit 111; }
safe() { "$@" || barf "cannot $@"; }

here=`env - PATH=$PATH pwd`
mypwd=${here%package}
mypwd=${mypwd%/}

sslfiles="ssl.lib ucspissl.a ucspissl.h"

home=`head -1 $mypwd/conf-ucspissl`

if [ -d $home ] 
then
  shout "Linking ucspi-ssl sources."
  for sfile in `echo $sslfiles`
  do 
    if [ -f $home/compile/$sfile ]
    then
      if [ ! -L "$mypwd/src/$sfile" ]
      then
        safe ln -s "$home/compile/$sfile" "$mypwd/src/$sfile"
      fi
#      safe touch "$mypwd/src/$sfile"
      safe ls -l "$mypwd/src/$sfile"
    else
      barf "ucspi-ssl file $file missing. s/qmail won't compile."
    fi
  done
else
  barf "Can't find ucspi-ssl dir. Check 'conf-ucspissl'."
fi 

exit 0
