#!/bin/sh
QMAILU=`id -u qmaild`
QMAILG=`id -g qmaild`
HOSTNAME=`hostname`
QMQP="628"
exec env PATH="/var/qmail/bin:$PATH" \
     tcpserver -v -Rp -l $HOSTNAME \
     -Xx /var/qmail/control/rules.qmqpd.cdb \
     -u $QMAILU -g $QMAILG 0 $QMQP \
     qmail-qmqpd 2>&1
