#!/bin/sh
QMAILU=`id -u qmaild`
QMAILG=`id -g qmaild`
HOSTNAME=`hostname`
export SMTPAUTH="!"
export UCSPITLS=""
. /var/qmail/ssl/ssl.env
exec env PATH="/var/qmail/bin:/usr/local/bin:$PATH" \
     sslserver -seVn -Rp -l $HOSTNAME \
     -u $QMAILU -g $QMAILG 0 submission \
     qmail-smtpd qmail-authuser true 2>&1
