#!/bin/sh
HOSTNAME=`hostname`
. /var/qmail/ssl/ssl.env
exec env PATH="/var/qmail/bin:$PATH" \
     sslserver -seV -Rp -l $HOSTNAME 0 pop3s \
     qmail-popup $HOSTNAME qmail-authuser true \
     qmail-pop3d Maildir 2>&1 5>&1
