#!/bin/sh
QMAILU=`id -u qmaild`
QMAILG=`id -g qmaild`
HOSTNAME=`hostname`
exec env PATH="/var/qmail/bin:$PATH" \
     tcpserver -v -Rp -l $HOSTNAME \
     -Xx /var/qmail/control/rules.smtpd.cdb \
     -u $QMAILU -g $QMAILG 0 qmtp \
     qmail-qmtpd 2>&1
