#!/bin/sh
QMAILU=`id -u qmaild`
QMAILG=`id -g qmaild`
HOSTNAME=`hostname`
export UCSPITLS=""
export SPF="1"
. /var/qmail/ssl/ssl.env
exec env PATH="/var/qmail/bin:$PATH" \
     sslserver -seVn -Rp -l $HOSTNAME \
     -Xx /var/qmail/control/rules.smtpd.cdb \
     -u $QMAILU -g $QMAILG 0 smtp \
     qmail-smtpd 2>&1
