#!/bin/sh
QMAILU=`id -u qmaild`
QMAILG=`id -g qmaild`
QMTPS="6209"
HOSTNAME=`hostname`
. /var/qmail/ssl/ssl.env
exec env PATH="/var/qmail/bin:$PATH" \
     sslserver -seV -Rp -l $HOSTNAME \
     -Xx /var/qmail/control/rules.smtpd.cdb \
     -u $QMAILU -g $QMAILG 0 $QMTPS \
     qmail-qmtpd 2>&1
