#!/bin/sh
QMAILU=`id -u qmaild`
QMAILG=`id -g qmaild`
HOSTNAME=`hostname`
export SMTPAUTH=""
. /var/qmail/ssl/ssl.env
exec env PATH="/var/qmail/bin:/usr/local/bin:$PATH" \
     sslserver -seV -Rp -l $HOSTNAME \
     -Xx /var/qmail/control/rules.smtpd.cdb \
     -u $QMAILU -g $QMAILG 0 smtps \
     qmail-smtpd qmail-authuser true 2>&1
