#!/bin/sh -e
test -d compile || ( echo 'Wrong working directory.'; exit 1 )
here=`env - PATH=$PATH pwd`
( echo sqmail-`head -1 package/version`
  echo $here
  if test -r compile/sysdeps
  then
    cat compile/sysdeps
  fi
) | mail sqmail@fehcom.de
